apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.10.4
  count: 1
  elasticsearchRef:
    name: quickstart
  http:
    service:
      spec:
        type: NodePort
        ports:
        - name: http
          port: 5601
          targetPort: 5601
          protocol: TCP
          nodePort: 31310
